/PMACRO
!    Demonstartion of mulitprompt.tk
WIDTH=4.5
HEIGHT=3.2
RADIUS=0.45
MultiPro='TEST'
*del,TESTTitl
*dim,TESTTitl,string,64
TESTTitl(1,1) = 'Test of multiprompt macro'
*del,TESTDesc
*dim,TESTDesc,string,32,3
TESTDesc(1,1)='Description of Parameter WIDTH'
TESTDesc(1,2)='Description of Parameter HEIGHT'
TESTDesc(1,3)='Description of Parameter RADIUS'
*del,TESTParm
*dim,TESTParm,char,3
TestParm(1)='WIDTH'
TestParm(2)='HEIGHT'
TestParm(3)='RADIUS'

)~eui,'source multiprompt.tk'

